// SENDER & GCM Registration Token

const GCM_ACCOUNT = {
    SENDER: 'AIzaSyCTjFXhiconyIyI6eSFzlUgE16DC97lNiU',
    TOKEN: 'crubzHWU278:APA91bEgwUU5swN-YW2nyU2e4m5JC-0jQ8FJwjc063yPTHwwGJKpGfubYF0yyTfeR2KEEgY4ah-XIyVgDGqe783V0O5fgWATgVG-USUkjdF_X3xK7uiMNsMWVOFQQdZohUUMmzLTICWq'    
}

export { GCM_ACCOUNT }